# Generated by Django 5.2.4 on 2025-08-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("venue", models.CharField(max_length=255)),
                ("total_seats", models.IntegerField()),
                ("available_seats", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
