# Generated by Django 5.2.4 on 2025-08-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(default="Miasto", max_length=255),
            preserve_default=False,
        ),
    ]
