# Generated by Django 5.2.4 on 2025-08-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="highlights",
            field=models.TextField(blank=True),
        ),
    ]
