# Generated by Django 5.2.4 on 2025-09-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_description_event_highlights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="event",
            name="highlights",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
