# Generated by Django 5.2.4 on 2025-10-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_city_alter_event_highlights"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="seating_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="venues.seatingplan",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="venues.venuearea",
            ),
        ),
        migrations.CreateModel(
            name="EventSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_reserved", models.BooleanField(default=False)),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_seats",
                        to="events.event",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_seats",
                        to="venues.seat",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["event", "is_reserved"],
                        name="events_even_event_i_62706c_idx",
                    )
                ],
                "unique_together": {("event", "seat")},
            },
        ),
    ]
