# Generated by Django 5.2.4 on 2025-10-29 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_seating_plan_event_venue_area_eventseat"),
        ("venues", "0003_alter_section_price_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="venues.venue",
                verbose_name="Obiekt",
            ),
        ),
    ]
