# Generated by Django 5.2.4 on 2025-10-29 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_alter_event_venue"),
        ("venues", "0003_alter_section_price_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="venues.venue",
                verbose_name="Obiekt",
            ),
        ),
    ]
