# Generated by Django 5.2.4 on 2025-10-29 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_alter_event_venue"),
        ("venues", "0003_alter_section_price_modifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventseat",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_seats",
                to="venues.section",
            ),
        ),
        migrations.AlterField(
            model_name="eventseat",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_seats",
                to="venues.seat",
            ),
        ),
    ]
