# Generated by Django 5.2.4 on 2025-11-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventseat_section_alter_eventseat_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventseat',
            name='section',
        ),
    ]
