# Generated by Django 5.2.4 on 2025-09-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PLN', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(choices=[('dummy', 'Dummy'), ('p24', 'P24'), ('payu', 'Payu'), ('blik', 'Blik')], default='dummy', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text='External ID for this payment', max_length=255, null=True)),
                ('status', models.CharField(choices=[('created', 'Utworzona'), ('pending', 'Oczekująca'), ('authorized', 'Autoryzowana'), ('succeeded', 'Zakończona pomyślnie'), ('failed', 'Nieudana'), ('canceled', 'Anulowana')], db_index=True, default='created', max_length=20)),
                ('payer_email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
            ],
            options={
                'verbose_name': 'Płatność',
                'verbose_name_plural': 'Płatności',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['provider', 'external_id'], name='payments_pa_provide_4a6ba4_idx')],
            },
        ),
    ]
