# Generated by Django 5.2.4 on 2025-08-24 13:28

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_profile_picture_path),
        ),
    ]
