# Generated by Django 5.2.4 on 2025-10-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("super_user", "Super User"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
