# Generated by Django 5.2.4 on 2025-10-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_user'),
        ('booking', '0002_remove_booking_event_remove_booking_full_name_and_more'),
    ]

    operations = [
    ]
