# Generated by Django 5.2.4 on 2025-10-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_merge_20251026_1943"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_seats",
                        to="booking.bookingitem",
                    ),
                ),
            ],
        ),
    ]
