# Generated by Django 5.2.4 on 2025-10-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_ticketseat"),
        ("events", "0005_event_seating_plan_event_venue_area_eventseat"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketseat",
            name="event_seat",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_seat",
                to="events.eventseat",
            ),
        ),
    ]
