# Generated by Django 5.2.4 on 2025-10-27 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_ticketseat_event_seat"),
        ("events", "0005_event_seating_plan_event_venue_area_eventseat"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingitem",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="booking_items",
                to="events.eventseat",
                verbose_name="Zarezerwowane miejsce",
            ),
        ),
    ]
