# Generated by Django 5.2.4 on 2025-11-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_merge_20251026_1437'),
        ('booking', '0003_merge_20251026_1925'),
        ('booking', '0006_bookingitem_seat'),
    ]

    operations = [
    ]
