# Generated by Django 5.2.4 on 2025-11-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_merge_20251103_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='locked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-11-07 17:45:00'),
            preserve_default=False,
        ),
    ]
