# Generated by Django 5.2.4 on 2025-11-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_bookingitem_locked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
