# Generated by Django 5.2.4 on 2025-11-08 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookingitem_canceled_at_bookingitem_is_canceled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='canceled_at',
        ),
        migrations.RemoveField(
            model_name='bookingitem',
            name='is_canceled',
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='locked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
