# Generated by Django 5.2.4 on 2025-10-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Układ miejsc')),
            ],
            options={
                'verbose_name': 'Układ miejsc',
                'verbose_name_plural': 'Układy miejsc',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa obiektu')),
                ('city', models.CharField(max_length=100, verbose_name='Miejscowość')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adres')),
                ('pets_friendly', models.BooleanField(default=False, verbose_name='Wstęp ze zwierzętami')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Obiekt',
                'verbose_name_plural': 'Obiekty',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nazwa sektora')),
                ('type', models.CharField(choices=[('seated', 'Miejsca siedzące'), ('standing', 'Miejsca stojące')], default='seated', max_length=10, verbose_name='Typ sektora')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Dotyczy miejsc stojących.', verbose_name='Maksymalna liczba miejsc')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='venues.seatingplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Sektor',
                'verbose_name_plural': 'Sektory',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=10, verbose_name='Rząd')),
                ('number', models.CharField(max_length=10, verbose_name='Numer')),
                ('is_wheelchair', models.BooleanField(default=False, verbose_name='Miejsce dla osoby na wózku')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='venues.section', verbose_name='Sektor')),
            ],
            options={
                'verbose_name': 'Miejsce',
                'verbose_name_plural': 'Miejsca',
            },
        ),
        migrations.CreateModel(
            name='VenueArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa sali / obszaru')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='venues.venue', verbose_name='Obiekt')),
            ],
            options={
                'verbose_name': 'Sala / obszar obiektu',
                'verbose_name_plural': 'Sale / obszary obiektu',
            },
        ),
        migrations.AddField(
            model_name='seatingplan',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='venues.venuearea', verbose_name='Sala / obszar obiektu'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('plan', 'name'), name='uniq_section_per_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('section', 'row', 'number'), name='uniq_seat_per_section_row_number'),
        ),
        migrations.AddConstraint(
            model_name='venuearea',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='uniq_venuearea_per_venue_name'),
        ),
        migrations.AddConstraint(
            model_name='seatingplan',
            constraint=models.UniqueConstraint(fields=('area', 'title'), name='uniq_seatingplan_per_area_title'),
        ),
    ]
