# Generated by Django 5.2.4 on 2025-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="price_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Dodatkowa cena za miejsca w tym sektorze",
                max_digits=8,
                verbose_name="Dopłata do ceny bazowej",
            ),
        ),
    ]
