# Generated by Django 5.2.4 on 2025-10-27 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_section_price_modifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="price_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="VIP +150, Balkon +60, Płyta 0",
                max_digits=8,
                verbose_name="Dopłata do ceny bazowej",
            ),
        ),
    ]
